"use client";

import Link from "next/link";
import { createEtabsHandoff, type ReadinessStatus } from "../lib/etabs-handoff";
import { useProjects } from "./project-provider";

const number = (value: number | null | undefined, unit = "") => value === null || value === undefined || !Number.isFinite(value) ? "—" : `${value.toLocaleString("id-ID", { maximumFractionDigits: 4 })}${unit ? ` ${unit}` : ""}`;

function Section({ title, source, href, children }: { title: string; source: string; href: string; children: React.ReactNode }) {
  return <section className="panel etabs-section"><header className="etabs-section-heading"><div><h2>{title}</h2><small>{source}</small></div><Link href={href}>Edit di sumber ↗</Link></header>{children}</section>;
}

function Status({ value }: { value: ReadinessStatus }) {
  return <strong className={`etabs-status is-${value.toLowerCase()}`}>{value}</strong>;
}

export function EtabsWorkspace() {
  const { active, createProject } = useProjects();
  if (!active) return <section className="panel empty-project"><h2>Belum ada proyek</h2><p>Buat proyek untuk melihat ringkasan Input ETABS.</p><button className="button button-primary" type="button" onClick={() => void createProject()}>Buat Proyek</button></section>;
  const handoff = createEtabsHandoff(active);
  const { result, materials, rawSeismic } = handoff;
  const seismicFields: [string, number | string | null | undefined, string, string][] = [
    ["Site Class", rawSeismic.site_class, "", "INPUT"], ["Ss", rawSeismic.ss, "g", "INPUT"], ["S1", rawSeismic.s1, "g", "INPUT"], ["TL", rawSeismic.tl, "s", "INPUT"],
    ["Fa", rawSeismic.fa, "", "INPUT"], ["Fv", rawSeismic.fv, "", "INPUT"],
    ...(["sms", "sm1", "sds", "sd1", "t0", "ts"] as const).map((key): [string, number | undefined, string, string] => [key.toUpperCase(), result?.spectrum?.[key].value, result?.spectrum?.[key].unit ?? "", "AUTO"]),
    ["KDS", result?.kds_review?.governing_kds, "", "CODE"], ["Sistem struktur", handoff.selectedSystem?.label, "", "SELECTED"],
    ...(["R", "omega0", "Cd", "Ct", "x"] as const).map((key): [string, number | undefined, string, string] => [key === "omega0" ? "Ω0" : key, result?.system_parameters?.[key].value, result?.system_parameters?.[key].unit ?? "", "CODE"]),
    ["Ta", result?.period?.ta.value, "s", "AUTO"], ["Cu", result?.period?.cu.value, "", "CODE"], ["Tmax", result?.period?.tmax.value, "s", "AUTO"],
    ["Cs governing", result?.response_coefficient?.governing.value, "", "AUTO"], ["W", result?.seismic_weight?.value, "kN", "INHERITED"], ["V", result?.base_shear?.value, "kN", "AUTO"],
  ];
  return <div className="etabs-workspace">
    <div className="etabs-content">
      <section className={`panel etabs-hero is-${handoff.status.toLowerCase()}`} aria-live="polite"><div><p className="eyebrow">Handoff manual · revisi {handoff.revision}</p><h2>Kesiapan pemodelan ETABS <Status value={handoff.status} /></h2><p>{handoff.status === "BLOCKED" ? "Lengkapi item BLOCKED sebelum pemodelan. Asumsi yang belum dimodelkan tetap perlu review engineer." : "Data wajib Stage 1 siap; item WARNING dikonfirmasi dalam pekerjaan ETABS."}</p>{handoff.stale && <p className="etabs-stale">Hasil seismik perlu dihitung dan disimpan ulang setelah perubahan upstream.</p>}</div><small>Proyek revisi {handoff.revision} · {handoff.revisionId}<br />Registry {handoff.registryVersion}</small></section>
      <Section title="Grid System" source={`M3 Geometry · revisi ${handoff.revision}`} href="/geometri-model"><div className="etabs-two-columns">{handoff.grids.map((grid) => <div key={grid.axis}><h3>Grid {grid.axis}</h3><div className="table-scroll"><table className="seismic-table"><thead><tr><th>Label</th><th>Ordinat (m)</th><th>Jarak sebelumnya (m)</th></tr></thead><tbody>{grid.lines.map((line, index) => <tr key={line.label}><td>{line.label}</td><td>{number(line.ordinate)}</td><td>{index ? number(grid.spacings[index - 1]) : "—"}</td></tr>)}</tbody></table></div></div>)}</div></Section>
      <Section title="Story Data" source={`M3 Geometry · revisi ${handoff.revision}`} href="/geometri-model"><div className="table-scroll"><table className="seismic-table"><thead><tr><th>Story</th><th>Tinggi (m)</th><th>Elevasi (m)</th></tr></thead><tbody>{handoff.stories.map((story) => <tr key={story.order}><td>{story.name}</td><td>{number(story.height)}</td><td>{number(story.elevation)}</td></tr>)}</tbody></table></div></Section>
      <Section title="Material Properties" source={`M4 Material · revisi ${handoff.revision}`} href="/material"><div className="table-scroll"><table className="seismic-table"><thead><tr><th>Material</th><th>Mutu</th><th>Properti</th><th>Provenance</th></tr></thead><tbody>
        <tr><td>Beton</td><td>{materials.concrete.grade || "—"}</td><td>fc′ {number(materials.concrete.fc.value, "MPa")} · ρ {number(materials.concrete.density.value, "kg/m³")} · cover {number(materials.concrete.cover.value, "mm")}</td><td>INPUT</td></tr>
        <tr><td>Beton · Ec</td><td>—</td><td>{number(materials.concrete.elastic_modulus.value, "MPa")}</td><td>{materials.concrete.elastic_modulus.provenance} · {materials.concrete.elastic_modulus.formula_id ?? "belum tersedia"}</td></tr>
        <tr><td>Tulangan longitudinal</td><td>{materials.longitudinal_rebar.grade || "—"}</td><td>fy {number(materials.longitudinal_rebar.fy.value, "MPa")}</td><td>{materials.longitudinal_rebar.fy.provenance}</td></tr>
        <tr><td>Tulangan transversal</td><td>{materials.transverse_rebar.grade || "—"}</td><td>fys {number(materials.transverse_rebar.fys.value, "MPa")}</td><td>{materials.transverse_rebar.fys.provenance}</td></tr>
        </tbody></table></div><p className="etabs-note">Diameter tersedia: {materials.available_diameters.map(({ nominal_diameter }) => number(nominal_diameter.value, "mm")).join(", ") || "—"}</p></Section>
      <Section title="Section / Element Assumptions" source="M3 Geometry · belum ada definisi section/elemen" href="/geometri-model"><p className="etabs-review">WARNING · Dimensi, section, konektivitas, dan assignment elemen belum tersedia dalam model. Engineer perlu menetapkannya saat pemodelan ETABS.</p></Section>
      <Section title="Boundary / Restraint" source="M3 Geometry · asumsi belum tersimpan" href="/geometri-model"><p className="etabs-review">WARNING · Kondisi tumpuan dan restraint belum didefinisikan. Perlu review engineer sebelum input ETABS.</p></Section>
      <Section title="Load Patterns" source={`M5 Loads · revisi ${handoff.revision}`} href="/pembebanan"><div className="table-scroll"><table className="seismic-table"><thead><tr><th>Nama</th><th>Kategori</th><th>Nilai</th><th>Assignment</th><th>Self-weight multiplier</th><th>Sumber</th></tr></thead><tbody>{handoff.patterns.map((pattern) => <tr key={pattern.id}><td>{pattern.name}</td><td>{pattern.categoryLabel}</td><td>{number(pattern.value, pattern.unit)}</td><td>{pattern.assignmentCount}</td><td>Perlu review · belum tersimpan</td><td>{pattern.source || "—"} · {pattern.provenance}</td></tr>)}</tbody></table></div></Section>
      <Section title="Load Assignments" source={`M5 Loads · revisi ${handoff.revision}`} href="/pembebanan"><div className="table-scroll"><table className="seismic-table"><thead><tr><th>Load</th><th>Target</th><th>Aplikasi</th><th>Nilai</th><th>Asumsi / provenance</th></tr></thead><tbody>{handoff.assignments.map((assignment) => <tr key={assignment.id}><td>{assignment.definition?.name ?? assignment.load_id}</td><td>{assignment.target?.label ?? `${assignment.target_id} · tidak valid`}</td><td>{assignment.application}</td><td>{number(assignment.definition?.value, assignment.definition?.unit)}</td><td>{assignment.assumption} · {assignment.provenance}</td></tr>)}</tbody></table></div>{!handoff.assignments.length && <p className="etabs-note">Belum ada assignment.</p>}</Section>
      <Section title="Seismic Parameters" source={`M6 Seismic · revisi ${handoff.revision} · registry ${handoff.registryVersion}`} href="/analisa-gempa"><div className="etabs-field-grid">{seismicFields.map(([label, value, unit, provenance]) => <div key={label}><span>{label} <small>{provenance}</small></span><strong>{typeof value === "number" ? number(value, unit) : value || "—"}</strong></div>)}</div><p className="etabs-note">Ss, S1, TL, Fa, Fv: sumber dan penginput dari M6. {Object.entries(handoff.inputProvenance).map(([key, entry]) => `${key}: ${entry.source || "—"} / ${entry.entered_by || "—"}`).join(" · ")}</p></Section>
      <Section title="Load Cases" source={`M5/M6 · revisi ${handoff.revision}`} href="/pembebanan"><p className="etabs-review">Daftar review untuk pembuatan case manual. Jenis case, arah analisis, dan faktor belum ditetapkan oleh model proyek.</p><div className="table-scroll"><table className="seismic-table"><thead><tr><th>Sumber / nama</th><th>Kategori</th><th>Setup ETABS</th></tr></thead><tbody>{handoff.loadCases.map((item) => <tr key={item.id}><td>{item.source} · {item.name}</td><td>{item.category}</td><td>Perlu ditentukan engineer</td></tr>)}</tbody></table></div></Section>
      <Section title="Load Combinations" source={`Referensi proyek · registry ${handoff.combinationRegistryVersion} · ${handoff.combinationStatus}`} href="/pembebanan">{handoff.combinations.length ? <div className="table-scroll"><table className="seismic-table"><thead><tr><th>ID</th><th>Kombinasi</th><th>Referensi</th></tr></thead><tbody>{handoff.combinations.map((rule) => <tr key={rule.id}><td>{rule.id}</td><td>{rule.expression}</td><td>{rule.standard_ref}</td></tr>)}</tbody></table></div> : <p className="etabs-note">REFERENCE · {handoff.combinationNote || "Belum ada kombinasi referensi pada proyek."} Kombinasi disiapkan dan dijalankan di ETABS; kondisi ini tidak memblokir kesiapan Stage 1.</p>}</Section>
      <Section title="Response Spectrum Setup" source={`M6 Seismic · ${handoff.spectrumSource} · registry ${handoff.registryVersion}`} href="/analisa-gempa"><p className="etabs-note">Fungsi spektrum desain Sa(T) dari M6 · periode T (s), percepatan Sa (g). Damping dan faktor skala belum tersimpan; perlu review engineer. Tidak ada nilai skala yang diasumsikan.</p>{handoff.spectrum.length ? <div className="table-scroll etabs-spectrum"><table className="seismic-table"><thead><tr><th>T (s)</th><th>Sa (g)</th><th>Formula ID</th></tr></thead><tbody>{handoff.spectrum.map((point) => <tr key={point.period}><td>{number(point.period)}</td><td>{number(point.acceleration.value)}</td><td>{point.acceleration.formula_id}</td></tr>)}</tbody></table></div> : <p className="etabs-review">BLOCKED · Tabel spektrum belum tersedia untuk hasil M6 aktif.</p>}</Section>
    </div>
    <aside className="panel etabs-checklist" aria-label="Checklist kesiapan Stage 1"><h2>Readiness Checklist</h2><p>Revisi {handoff.revision} · <Status value={handoff.status} /></p><ul>{handoff.readiness.map((item) => <li key={item.label}><div><strong>{item.label}</strong><Status value={item.status} /></div><small>{item.classification.replaceAll("_", " ")}</small><p>{item.detail}</p><Link href={item.href}>Edit di sumber ↗</Link></li>)}</ul></aside>
  </div>;
}
